make scripts less bad & fix shellchecks

diff --git a/script/burn-cd b/script/burn-cd
--- a/script/burn-cd
+++ b/script/burn-cd
@@ -25,12 +25,10 @@ ISO=$TMP_DIR/temp.iso
 
 # generate iso from directory
 echo "INFO: generating iso from directory \"$DIR\""
-fail_with_msg \
-    "failed to create ISO from directory: $DIR" \
-    mkisofs -r -iso-level 4 -o "$ISO" "$DIR" > /dev/null
+fail_with_stderr mkisofs -r -iso-level 4 -o "$ISO" "$DIR" > /dev/null
 
 if [ ! -f "$ISO" ]; then
-    >&2 echo "ERROR: failed to create iso, not a file: \"$ISO\""
+    >&2 echo "ERROR: ISO successfully created but \"$ISO\" is not a file"
 fi
 
 # get hash of iso
@@ -41,20 +39,4 @@ echo "INFO: ISO has hash sha256-$ISO_HASH"
 # using 'fail_with_msg' so we do it manually.
 echo "INFO: writing ISO to device: \"$CD_DEV\""
 
-if ! cdrecord -silent -data "$ISO" dev="$CD_DEV" > /dev/null 2>&1; then
-    >&2 echo "ERROR: failed writing ISO to \"$CD_DEV\""
-    exit 1
-fi
-
-if ! eject "$CD_DEV"; then
-    >&2 echo "ERROR: failed to eject \"$CD_DEV\", press the button instead?"
-    exit 1
-fi
-
-# NOTE: This would be a good place to hash the cdrom to ensure the hash of
-# the ISO and the CD burned match. Accessing the cdrom immediately after
-# burning it fails in testing however. The alternative is to eject the CD
-# immediately after it's burned, then have the user reinsert the CD to
-# calculate the hash again.
-
-exit 0
+fail_with_stderr cdrecord -data "$ISO" dev="$CD_DEV" > /dev/null
